export let FALLBACK_SHOPS = [
  {
    _id: 'b0000000-0000-0000-0000-000000000001',
    id: 'b0000000-0000-0000-0000-000000000001',
    owner_id: 'a0000000-0000-0000-0000-000000000002',
    shopName: 'Sharma Hardware & Daily Essentials Store',
    tagline: 'Authorized Dealer • Genuine Goods & Construction Supplies',
    description: 'Trusted neighborhood hardware and daily essentials supplier serving Karol Bagh for 22+ years. Genuine pipes, tools, groceries and rapid counter collection.',
    category: 'Hardware & Tools',
    address: {
      street: 'Shop 14, Block 8, Ajmal Khan Road',
      area: 'Karol Bagh',
      city: 'New Delhi',
      state: 'Delhi',
      pincode: '110005',
    },
    location: {
      type: 'Point',
      coordinates: [77.1906, 28.6517],
    },
    contactPhone: '+91 9876543210',
    bannerImage: 'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    numReviews: 142,
    isActive: true,
    verificationStatus: 'verified',
    liveServingCount: 2,
    estWaitTimeMinutes: 4,
    promptResponseRate: 98,
    distanceKm: 0.8,
    openingHours: { open: '08:30 AM', close: '09:00 PM', isOpenNow: true },
  },
  {
    _id: 'b0000000-0000-0000-0000-000000000002',
    id: 'b0000000-0000-0000-0000-000000000002',
    owner_id: 'a0000000-0000-0000-0000-000000000003',
    shopName: 'Gupta Building Materials & Hardware',
    tagline: 'Complete Cement, Pipes & Sanitary Solutions',
    description: 'Wholesale and retail supplier of top plumbing, CPVC fittings, and building materials.',
    category: 'Hardware & Tools',
    address: {
      street: 'Plot 22, Connaught Circus',
      area: 'Connaught Place',
      city: 'New Delhi',
      state: 'Delhi',
      pincode: '110001',
    },
    location: {
      type: 'Point',
      coordinates: [77.2177, 28.6304],
    },
    contactPhone: '+91 9876543211',
    bannerImage: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    numReviews: 98,
    isActive: true,
    verificationStatus: 'verified',
    liveServingCount: 4,
    estWaitTimeMinutes: 8,
    promptResponseRate: 92,
    distanceKm: 2.3,
    openingHours: { open: '09:00 AM', close: '08:30 PM', isOpenNow: true },
  },
  {
    _id: 'b0000000-0000-0000-0000-000000000003',
    id: 'b0000000-0000-0000-0000-000000000003',
    owner_id: 'a0000000-0000-0000-0000-000000000005',
    shopName: 'City Plumbing & Daily Goods',
    tagline: 'Direct CPVC, UPVC, Valves & Essentials',
    description: 'Specialized merchant stocking Astral, Supreme, and essential provisions with instant counter collection.',
    category: 'Plumbing & Sanitary',
    address: {
      street: 'Shop 5, Central Market, Lajpat Nagar II',
      area: 'Lajpat Nagar',
      city: 'New Delhi',
      state: 'Delhi',
      pincode: '110024',
    },
    location: {
      type: 'Point',
      coordinates: [77.2433, 28.5700],
    },
    contactPhone: '+91 9876543212',
    bannerImage: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?auto=format&fit=crop&w=800&q=80',
    rating: 4.6,
    numReviews: 64,
    isActive: true,
    verificationStatus: 'verified',
    liveServingCount: 1,
    estWaitTimeMinutes: 3,
    promptResponseRate: 96,
    distanceKm: 9.8,
    openingHours: { open: '09:30 AM', close: '09:00 PM', isOpenNow: true },
  },
  {
    _id: 'b0000000-0000-0000-0000-000000000004',
    id: 'b0000000-0000-0000-0000-000000000004',
    owner_id: 'a0000000-0000-0000-0000-000000000006',
    shopName: 'Noida Metro Mart & Hardware',
    tagline: 'Comprehensive Industrial & Daily Hub',
    description: 'Sector 62 superstore providing electrical fittings, plumbing, and bulk provisions.',
    category: 'Hardware & Tools',
    address: {
      street: 'Tower B, Sector 62',
      area: 'Noida',
      city: 'Noida',
      state: 'Uttar Pradesh',
      pincode: '201309',
    },
    location: {
      type: 'Point',
      coordinates: [77.3639, 28.6256],
    },
    contactPhone: '+91 9876543213',
    bannerImage: 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    numReviews: 110,
    isActive: true,
    verificationStatus: 'verified',
    liveServingCount: 3,
    estWaitTimeMinutes: 6,
    promptResponseRate: 94,
    distanceKm: 18.5,
    openingHours: { open: '08:00 AM', close: '10:00 PM', isOpenNow: true },
  },
  {
    _id: 'sehore-demo-001',
    id: 'sehore-demo-001',
    owner_id: 'a0000000-0000-0000-0000-000000000011',
    ownerName: 'Suresh Patidar',
    shopName: 'Kothri Kalan Kirana & General Store',
    tagline: 'Daily essentials next to the VIT Bhopal campus',
    description: 'Trusted grocery and daily essentials supplier right next to the VIT Bhopal University campus in Kothri Kalan. Fresh staples, snacks, dairy and instant pickups.',
    landmark: 'Kothri Kalan village market, 10 min from VIT Bhopal',
    category: 'Groceries & Daily Essentials',
    address: {
      street: 'Main Village Road, Kothri Kalan',
      area: 'Kothri Kalan',
      city: 'Kothri Kalan, Sehore',
      state: 'Madhya Pradesh',
      pincode: '466114',
    },
    location: {
      type: 'Point',
      coordinates: [76.8298, 23.074],
    },
    contactPhone: '+91 90000 00001',
    bannerImage: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80',
    rating: 4.6,
    numReviews: 84,
    isActive: true,
    verificationStatus: 'verified',
    liveServingCount: 2,
    estWaitTimeMinutes: 5,
    promptResponseRate: 97,
    distanceKm: 2.1,
    deliveryAvailable: true,
    deliveryEtaMinutes: 25,
    totalSalesVolume: 145000,
    openingHours: { open: '06:30 AM', close: '09:30 PM', isOpenNow: true },
  },
  {
    _id: 'sehore-demo-002',
    id: 'sehore-demo-002',
    owner_id: 'a0000000-0000-0000-0000-000000000012',
    ownerName: 'Ramesh Malviya',
    shopName: 'Ashta Hardware & Sanitation Mart',
    tagline: 'Tools, paints and sanitary fittings in Ashta Main Market',
    description: 'Comprehensive hardware, hand tools, Astral/Finolex plumbing pipes and Asian Paints in the heart of Ashta Main Market.',
    landmark: 'Main Market, near Ashta town square',
    category: 'Hardware & Tools',
    address: {
      street: 'Main Market, Near Town Square',
      area: 'Ashta',
      city: 'Ashta, Sehore',
      state: 'Madhya Pradesh',
      pincode: '466116',
    },
    location: {
      type: 'Point',
      coordinates: [76.7222, 23.0195],
    },
    contactPhone: '+91 90000 00002',
    bannerImage: 'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?auto=format&fit=crop&w=800&q=80',
    rating: 4.4,
    numReviews: 61,
    isActive: true,
    verificationStatus: 'verified',
    liveServingCount: 3,
    estWaitTimeMinutes: 8,
    promptResponseRate: 91,
    distanceKm: 14.5,
    deliveryAvailable: false,
    deliveryEtaMinutes: null,
    totalSalesVolume: 188000,
    openingHours: { open: '09:00 AM', close: '09:00 PM', isOpenNow: true },
  },
  {
    _id: 'sehore-demo-003',
    id: 'sehore-demo-003',
    owner_id: 'a0000000-0000-0000-0000-000000000013',
    ownerName: 'Dinesh Patel',
    shopName: 'Ashta Electrical & Farm Centre',
    tagline: 'Wires, pumps and lighting for farms and homes',
    description: 'Heavy-duty agricultural water pumps, Polycab copper wires, Anchor modular switches and farm electrical accessories in Ashta.',
    landmark: 'Krishi Mandi Road, Ashta',
    category: 'Electrical & Lighting',
    address: {
      street: 'Krishi Mandi Road, Ashta',
      area: 'Ashta',
      city: 'Ashta, Sehore',
      state: 'Madhya Pradesh',
      pincode: '466116',
    },
    location: {
      type: 'Point',
      coordinates: [76.715, 23.018],
    },
    contactPhone: '+91 90000 00003',
    bannerImage: 'https://images.unsplash.com/photo-1555963966-b7ae5404b6ed?auto=format&fit=crop&w=800&q=80',
    rating: 4.3,
    numReviews: 47,
    isActive: true,
    verificationStatus: 'verified',
    liveServingCount: 1,
    estWaitTimeMinutes: 4,
    promptResponseRate: 93,
    distanceKm: 15.2,
    deliveryAvailable: true,
    deliveryEtaMinutes: 70,
    totalSalesVolume: 112000,
    openingHours: { open: '08:30 AM', close: '08:30 PM', isOpenNow: true },
  },
  {
    _id: 'sehore-demo-004',
    id: 'sehore-demo-004',
    owner_id: 'a0000000-0000-0000-0000-000000000014',
    ownerName: 'Dr. R.K. Verma',
    shopName: 'Ashta Civil Medical Store',
    tagline: 'Medicines and wellness essentials opposite Civil Hospital Ashta',
    description: '24x7 verified pharmacy providing emergency medicines, first-aid, hydration salts, bandages and clinical thermometers opposite Ashta Civil Hospital.',
    landmark: 'SH-70, opposite Civil Hospital Ashta',
    category: 'Medicines & Wellness',
    address: {
      street: 'SH-70, Opposite Civil Hospital Ashta',
      area: 'Ashta',
      city: 'Ashta, Sehore',
      state: 'Madhya Pradesh',
      pincode: '466116',
    },
    location: {
      type: 'Point',
      coordinates: [76.7245, 23.0227],
    },
    contactPhone: '+91 90000 00004',
    bannerImage: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    numReviews: 126,
    isActive: true,
    verificationStatus: 'verified',
    liveServingCount: 4,
    estWaitTimeMinutes: 3,
    promptResponseRate: 99,
    distanceKm: 14.1,
    deliveryAvailable: true,
    deliveryEtaMinutes: 45,
    totalSalesVolume: 164000,
    openingHours: { open: '07:00 AM', close: '11:00 PM', isOpenNow: true },
  },
  {
    _id: 'sehore-demo-005',
    id: 'sehore-demo-005',
    owner_id: 'a0000000-0000-0000-0000-000000000015',
    ownerName: 'Sunil Lalwani',
    shopName: 'Bairagarh Electronics & Mobile Hub',
    tagline: 'Gadgets, chargers and accessories in Bairagarh, Bhopal',
    description: 'Smart chargers, earphones, wireless gadgets, power banks and consumer electronics in Bairagarh, Bhopal.',
    landmark: 'Bairagarh Main Road, Bhopal',
    category: 'Electronics & Mobiles',
    address: {
      street: 'Bairagarh Main Road, Near Bus Stop',
      area: 'Bairagarh',
      city: 'Bhopal',
      state: 'Madhya Pradesh',
      pincode: '462030',
    },
    location: {
      type: 'Point',
      coordinates: [77.3366, 23.2745],
    },
    contactPhone: '+91 90000 00005',
    bannerImage: 'https://images.unsplash.com/photo-1511707171634-5f00e5a94b69?auto=format&fit=crop&w=800&q=80',
    rating: 4.5,
    numReviews: 92,
    isActive: true,
    verificationStatus: 'verified',
    liveServingCount: 3,
    estWaitTimeMinutes: 7,
    promptResponseRate: 95,
    distanceKm: 54.6,
    deliveryAvailable: true,
    deliveryEtaMinutes: 90,
    totalSalesVolume: 230000,
    openingHours: { open: '10:00 AM', close: '09:30 PM', isOpenNow: true },
  },
  {
    _id: 'sehore-demo-006',
    id: 'sehore-demo-006',
    owner_id: 'a0000000-0000-0000-0000-000000000016',
    ownerName: 'Deepak Saxena',
    shopName: 'New Market Books & Stationery Corner',
    tagline: 'Books, notebooks and office supplies at New Market Bhopal',
    description: 'College textbooks, notebooks, drawing instruments, copier reams and office stationery at historic New Market Bhopal.',
    landmark: 'New Market, TT Nagar, Bhopal',
    category: 'Stationery & Office',
    address: {
      street: 'New Market, TT Nagar',
      area: 'New Market',
      city: 'Bhopal',
      state: 'Madhya Pradesh',
      pincode: '462001',
    },
    location: {
      type: 'Point',
      coordinates: [77.4003, 23.2352],
    },
    contactPhone: '+91 90000 00006',
    bannerImage: 'https://images.unsplash.com/photo-1456735190827-d1262f71b8a3?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    numReviews: 73,
    isActive: true,
    verificationStatus: 'verified',
    liveServingCount: 2,
    estWaitTimeMinutes: 5,
    promptResponseRate: 96,
    distanceKm: 59.1,
    deliveryAvailable: false,
    deliveryEtaMinutes: null,
    totalSalesVolume: 89000,
    openingHours: { open: '10:30 AM', close: '09:00 PM', isOpenNow: true },
  },
];

export let FALLBACK_PRODUCTS = [
  {
    _id: 'c0000000-0000-0000-0000-000000000001',
    id: 'c0000000-0000-0000-0000-000000000001',
    name: 'Finolex 1-inch Heavy Duty PVC Pipe (10ft)',
    brand: 'Finolex',
    description: 'High pressure heavy-duty PVC pipe for residential plumbing lines and drainage.',
    category: 'Plumbing & Sanitary',
    price: 290,
    mrp: 350,
    unit: 'piece',
    quantityInStock: 45,
    lowStockThreshold: 10,
    isAvailable: true,
    stockStatus: 'in_stock',
    images: ['https://images.unsplash.com/photo-1585771724684-38269d6639fd?auto=format&fit=crop&w=600&q=80'],
    tags: ['pipe', 'pvc', 'plumbing', 'finolex'],
    shopId: {
      _id: 'b0000000-0000-0000-0000-000000000001',
      id: 'b0000000-0000-0000-0000-000000000001',
      shopName: 'Sharma Hardware & Daily Essentials Store',
      rating: 4.9,
      address: { street: 'Shop 14, Block 8, Ajmal Khan Road', area: 'Karol Bagh', city: 'New Delhi' },
      location: { coordinates: [77.1906, 28.6517] }
    }
  },
  {
    _id: 'c0000000-0000-0000-0000-000000000002',
    id: 'c0000000-0000-0000-0000-000000000002',
    name: 'Astral CPVC Pro Pipe 1 inch (3 Meter)',
    brand: 'Astral',
    description: 'Lead-free hot and cold potable water plumbing pipe certified to ASTM standards.',
    category: 'Plumbing & Sanitary',
    price: 390,
    mrp: 460,
    unit: 'piece',
    quantityInStock: 3, // Low stock on purpose for testing warnings!
    lowStockThreshold: 5,
    isAvailable: true,
    stockStatus: 'low_stock',
    images: ['https://images.unsplash.com/photo-1542013936693-884638332954?auto=format&fit=crop&w=600&q=80'],
    tags: ['pipe', 'cpvc', 'astral', 'hot water'],
    shopId: {
      _id: 'b0000000-0000-0000-0000-000000000001',
      id: 'b0000000-0000-0000-0000-000000000001',
      shopName: 'Sharma Hardware & Daily Essentials Store',
      rating: 4.9,
      address: { street: 'Shop 14, Block 8, Ajmal Khan Road', area: 'Karol Bagh', city: 'New Delhi' },
      location: { coordinates: [77.1906, 28.6517] }
    }
  },
  {
    _id: 'c0000000-0000-0000-0000-000000000003',
    id: 'c0000000-0000-0000-0000-000000000003',
    name: 'Bosch Professional 500W Impact Drill Kit',
    brand: 'Bosch',
    description: 'Heavy duty multi-speed reversible impact drill machine with 10 drill bits and case.',
    category: 'Hardware & Tools',
    price: 2850,
    mrp: 3499,
    unit: 'kit',
    quantityInStock: 8,
    lowStockThreshold: 2,
    isAvailable: true,
    stockStatus: 'in_stock',
    images: ['https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=600&q=80'],
    tags: ['drill', 'bosch', 'tools', 'hardware'],
    shopId: {
      _id: 'b0000000-0000-0000-0000-000000000001',
      id: 'b0000000-0000-0000-0000-000000000001',
      shopName: 'Sharma Hardware & Daily Essentials Store',
      rating: 4.9,
      address: { street: 'Shop 14, Block 8, Ajmal Khan Road', area: 'Karol Bagh', city: 'New Delhi' },
      location: { coordinates: [77.1906, 28.6517] }
    }
  },
  {
    _id: 'c0000000-0000-0000-0000-000000000004',
    id: 'c0000000-0000-0000-0000-000000000004',
    name: 'Amul Taaza Milk 1L',
    brand: 'Amul',
    description: 'Pasteurised toned milk with 3.0% fat, fresh and wholesome for daily family nutrition.',
    category: 'Groceries & Daily Essentials',
    price: 65,
    mrp: 66,
    unit: 'pouch',
    quantityInStock: 8,
    lowStockThreshold: 4,
    isAvailable: true,
    stockStatus: 'in_stock',
    images: ['https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=600&q=80'],
    tags: ['milk', 'amul', 'dairy', 'daily'],
    shopId: {
      _id: 'b0000000-0000-0000-0000-000000000001',
      id: 'b0000000-0000-0000-0000-000000000001',
      shopName: 'Sharma Hardware & Daily Essentials Store',
      rating: 4.9,
      address: { street: 'Shop 14, Block 8, Ajmal Khan Road', area: 'Karol Bagh', city: 'New Delhi' },
      location: { coordinates: [77.1906, 28.6517] }
    }
  },
  {
    _id: 'c0000000-0000-0000-0000-000000000005',
    id: 'c0000000-0000-0000-0000-000000000005',
    name: 'Aashirvaad Shudh Chakki Atta (5kg)',
    brand: 'Aashirvaad',
    description: '100% pure whole wheat grain flour with 0% maida for soft and fluffy rotis.',
    category: 'Groceries & Daily Essentials',
    price: 245,
    mrp: 275,
    unit: 'bag',
    quantityInStock: 14,
    lowStockThreshold: 5,
    isAvailable: true,
    stockStatus: 'in_stock',
    images: ['https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80'],
    tags: ['atta', 'flour', 'wheat', 'groceries'],
    shopId: {
      _id: 'b0000000-0000-0000-0000-000000000001',
      id: 'b0000000-0000-0000-0000-000000000001',
      shopName: 'Sharma Hardware & Daily Essentials Store',
      rating: 4.9,
      address: { street: 'Shop 14, Block 8, Ajmal Khan Road', area: 'Karol Bagh', city: 'New Delhi' },
      location: { coordinates: [77.1906, 28.6517] }
    }
  },
  {
    _id: 'c0000000-0000-0000-0000-000000000006',
    id: 'c0000000-0000-0000-0000-000000000006',
    name: 'Tata Salt Vacuum Evaporated (1kg)',
    brand: 'Tata',
    description: 'Iodised vacuum-evaporated table salt ensuring iodine guarantee for healthy development.',
    category: 'Groceries & Daily Essentials',
    price: 28,
    mrp: 30,
    unit: 'packet',
    quantityInStock: 2, // Low stock warning!
    lowStockThreshold: 10,
    isAvailable: true,
    stockStatus: 'low_stock',
    images: ['https://images.unsplash.com/photo-1518110925495-5fe2fda0442c?auto=format&fit=crop&w=600&q=80'],
    tags: ['salt', 'tata', 'iodised', 'groceries'],
    shopId: {
      _id: 'b0000000-0000-0000-0000-000000000001',
      id: 'b0000000-0000-0000-0000-000000000001',
      shopName: 'Sharma Hardware & Daily Essentials Store',
      rating: 4.9,
      address: { street: 'Shop 14, Block 8, Ajmal Khan Road', area: 'Karol Bagh', city: 'New Delhi' },
      location: { coordinates: [77.1906, 28.6517] }
    }
  },
  {
    _id: 'c0000000-0000-0000-0000-000000000007',
    id: 'c0000000-0000-0000-0000-000000000007',
    name: 'Parle-G Gold Biscuits (1kg)',
    brand: 'Parle',
    description: 'Bigger, crispier and tastier glucose biscuits filled with goodness of milk and wheat.',
    category: 'Groceries & Daily Essentials',
    price: 130,
    mrp: 145,
    unit: 'pack',
    quantityInStock: 0, // Critically low / Out of stock on purpose!
    lowStockThreshold: 5,
    isAvailable: false,
    stockStatus: 'out_of_stock',
    images: ['https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=600&q=80'],
    tags: ['biscuits', 'parle-g', 'snacks'],
    shopId: {
      _id: 'b0000000-0000-0000-0000-000000000001',
      id: 'b0000000-0000-0000-0000-000000000001',
      shopName: 'Sharma Hardware & Daily Essentials Store',
      rating: 4.9,
      address: { street: 'Shop 14, Block 8, Ajmal Khan Road', area: 'Karol Bagh', city: 'New Delhi' },
      location: { coordinates: [77.1906, 28.6517] }
    }
  },
  {
    _id: 'c0000000-0000-0000-0000-000000000008',
    id: 'c0000000-0000-0000-0000-000000000008',
    name: 'Jaquar Brass Angle Valve with Flange',
    brand: 'Jaquar',
    description: 'Quarter turn high-durability chrome plated brass angle stop cock valve.',
    category: 'Plumbing & Sanitary',
    price: 480,
    mrp: 575,
    unit: 'piece',
    quantityInStock: 25,
    lowStockThreshold: 4,
    isAvailable: true,
    stockStatus: 'in_stock',
    images: ['https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80'],
    tags: ['valve', 'jaquar', 'bathroom'],
    shopId: {
      _id: 'b0000000-0000-0000-0000-000000000001',
      id: 'b0000000-0000-0000-0000-000000000001',
      shopName: 'Sharma Hardware & Daily Essentials Store',
      rating: 4.9,
      address: { street: 'Shop 14, Block 8, Ajmal Khan Road', area: 'Karol Bagh', city: 'New Delhi' },
      location: { coordinates: [77.1906, 28.6517] }
    }
  },

  // Kothri Kalan Kirana & General Store (VIT Bhopal)
  {
    _id: 'sehore-item-atta',
    id: 'sehore-item-atta',
    name: 'Shudh Chakki Atta 5kg',
    brand: 'Aashirvaad',
    category: 'Groceries & Daily Essentials',
    description: 'Premium whole wheat grain chakki fresh flour for nutritious rotis.',
    price: 245,
    mrp: 275,
    unit: 'bag',
    quantityInStock: 60,
    lowStockThreshold: 10,
    isAvailable: true,
    stockStatus: 'in_stock',
    images: ['https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=500&q=80'],
    tags: ['atta', 'flour', 'kothri', 'vit bhopal', 'sehore'],
    shopId: {
      _id: 'sehore-demo-001',
      id: 'sehore-demo-001',
      shopName: 'Kothri Kalan Kirana & General Store',
      rating: 4.6,
      address: { street: 'Main Village Road, Kothri Kalan', area: 'Kothri Kalan', city: 'Kothri Kalan, Sehore', state: 'Madhya Pradesh' },
      location: { coordinates: [76.8298, 23.074] }
    }
  },
  {
    _id: 'sehore-item-rice',
    id: 'sehore-item-rice',
    name: 'Everyday Basmati Rice 5kg',
    brand: 'India Gate',
    category: 'Groceries & Daily Essentials',
    description: 'Long grain aromatic aged basmati rice for daily meals.',
    price: 365,
    mrp: 420,
    unit: 'bag',
    quantityInStock: 2,
    lowStockThreshold: 5,
    isAvailable: true,
    stockStatus: 'low_stock',
    images: ['https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=500&q=80'],
    tags: ['rice', 'basmati', 'kothri', 'vit bhopal'],
    shopId: {
      _id: 'sehore-demo-001',
      id: 'sehore-demo-001',
      shopName: 'Kothri Kalan Kirana & General Store',
      rating: 4.6,
      address: { street: 'Main Village Road, Kothri Kalan', area: 'Kothri Kalan', city: 'Kothri Kalan, Sehore', state: 'Madhya Pradesh' },
      location: { coordinates: [76.8298, 23.074] }
    }
  },
  {
    _id: 'sehore-item-oil',
    id: 'sehore-item-oil',
    name: 'Sunflower Refined Oil 1L',
    brand: 'Fortune',
    category: 'Groceries & Daily Essentials',
    description: 'Light and healthy refined sunflower cooking oil with vitamins A & D.',
    price: 145,
    mrp: 160,
    unit: 'bottle',
    quantityInStock: 40,
    lowStockThreshold: 8,
    isAvailable: true,
    stockStatus: 'in_stock',
    images: ['https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=500&q=80'],
    tags: ['oil', 'fortune', 'kothri', 'vit bhopal'],
    shopId: {
      _id: 'sehore-demo-001',
      id: 'sehore-demo-001',
      shopName: 'Kothri Kalan Kirana & General Store',
      rating: 4.6,
      address: { street: 'Main Village Road, Kothri Kalan', area: 'Kothri Kalan', city: 'Kothri Kalan, Sehore', state: 'Madhya Pradesh' },
      location: { coordinates: [76.8298, 23.074] }
    }
  },
  {
    _id: 'sehore-item-salt',
    id: 'sehore-item-salt',
    name: 'Iodised Salt 1kg',
    brand: 'Tata',
    category: 'Groceries & Daily Essentials',
    description: 'Vacuum evaporated iodine enriched healthy table salt.',
    price: 24,
    mrp: 28,
    unit: 'pack',
    quantityInStock: 80,
    lowStockThreshold: 15,
    isAvailable: true,
    stockStatus: 'in_stock',
    images: ['https://images.unsplash.com/photo-1518110925495-5fe2fda0442c?auto=format&fit=crop&w=500&q=80'],
    tags: ['salt', 'tata', 'kothri'],
    shopId: {
      _id: 'sehore-demo-001',
      id: 'sehore-demo-001',
      shopName: 'Kothri Kalan Kirana & General Store',
      rating: 4.6,
      address: { street: 'Main Village Road, Kothri Kalan', area: 'Kothri Kalan', city: 'Kothri Kalan, Sehore', state: 'Madhya Pradesh' },
      location: { coordinates: [76.8298, 23.074] }
    }
  },
  {
    _id: 'sehore-item-tea',
    id: 'sehore-item-tea',
    name: 'Red Label Tea 500g',
    brand: 'Brooke Bond',
    category: 'Groceries & Daily Essentials',
    description: 'Strong Assam CTC black tea blend for energizing taste.',
    price: 265,
    mrp: 310,
    unit: 'pack',
    quantityInStock: 22,
    lowStockThreshold: 6,
    isAvailable: true,
    stockStatus: 'in_stock',
    images: ['https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=500&q=80'],
    tags: ['tea', 'chai', 'kothri', 'vit bhopal'],
    shopId: {
      _id: 'sehore-demo-001',
      id: 'sehore-demo-001',
      shopName: 'Kothri Kalan Kirana & General Store',
      rating: 4.6,
      address: { street: 'Main Village Road, Kothri Kalan', area: 'Kothri Kalan', city: 'Kothri Kalan, Sehore', state: 'Madhya Pradesh' },
      location: { coordinates: [76.8298, 23.074] }
    }
  },
  {
    _id: 'sehore-item-dal',
    id: 'sehore-item-dal',
    name: 'Toor Dal 1kg',
    brand: 'Tata Sampann',
    category: 'Groceries & Daily Essentials',
    description: 'Unpolished protein rich toor dal with natural nutrition.',
    price: 175,
    mrp: 205,
    unit: 'pack',
    quantityInStock: 4,
    lowStockThreshold: 5,
    isAvailable: true,
    stockStatus: 'low_stock',
    images: ['https://images.unsplash.com/photo-1585771724684-38269d6639fd?auto=format&fit=crop&w=500&q=80'],
    tags: ['dal', 'pulses', 'kothri'],
    shopId: {
      _id: 'sehore-demo-001',
      id: 'sehore-demo-001',
      shopName: 'Kothri Kalan Kirana & General Store',
      rating: 4.6,
      address: { street: 'Main Village Road, Kothri Kalan', area: 'Kothri Kalan', city: 'Kothri Kalan, Sehore', state: 'Madhya Pradesh' },
      location: { coordinates: [76.8298, 23.074] }
    }
  },

  // Ashta Hardware & Sanitation Mart
  {
    _id: 'sehore-item-pipe',
    id: 'sehore-item-pipe',
    name: 'PVC Pipe 1 inch (10ft)',
    brand: 'Finolex',
    category: 'Plumbing & Sanitary',
    description: 'Heavy duty Finolex rigid PVC pipe for plumbing and drainage.',
    price: 290,
    mrp: 350,
    unit: 'piece',
    quantityInStock: 45,
    lowStockThreshold: 8,
    isAvailable: true,
    stockStatus: 'in_stock',
    images: ['https://images.unsplash.com/photo-1585771724684-38269d6639fd?auto=format&fit=crop&w=500&q=80'],
    tags: ['pipe', 'pvc', 'plumbing', 'ashta', 'sehore'],
    shopId: {
      _id: 'sehore-demo-002',
      id: 'sehore-demo-002',
      shopName: 'Ashta Hardware & Sanitation Mart',
      rating: 4.4,
      address: { street: 'Main Market, Near Town Square', area: 'Ashta', city: 'Ashta, Sehore', state: 'Madhya Pradesh' },
      location: { coordinates: [76.7222, 23.0195] }
    }
  },
  {
    _id: 'sehore-item-valve',
    id: 'sehore-item-valve',
    name: 'Brass Angle Valve with Flange',
    brand: 'Jaquar',
    category: 'Plumbing & Sanitary',
    description: 'Chrome plated premium quarter-turn angle stop cock valve.',
    price: 480,
    mrp: 575,
    unit: 'piece',
    quantityInStock: 5,
    lowStockThreshold: 8,
    isAvailable: true,
    stockStatus: 'low_stock',
    images: ['https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=500&q=80'],
    tags: ['valve', 'jaquar', 'ashta'],
    shopId: {
      _id: 'sehore-demo-002',
      id: 'sehore-demo-002',
      shopName: 'Ashta Hardware & Sanitation Mart',
      rating: 4.4,
      address: { street: 'Main Market, Near Town Square', area: 'Ashta', city: 'Ashta, Sehore', state: 'Madhya Pradesh' },
      location: { coordinates: [76.7222, 23.0195] }
    }
  },
  {
    _id: 'sehore-item-drill',
    id: 'sehore-item-drill',
    name: '500W Impact Drill Kit',
    brand: 'Bosch',
    category: 'Hardware & Tools',
    description: 'Professional reversible impact drill machine kit with carrying box.',
    price: 2850,
    mrp: 3499,
    unit: 'kit',
    quantityInStock: 20,
    lowStockThreshold: 4,
    isAvailable: true,
    stockStatus: 'in_stock',
    images: ['https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=500&q=80'],
    tags: ['drill', 'bosch', 'tools', 'ashta'],
    shopId: {
      _id: 'sehore-demo-002',
      id: 'sehore-demo-002',
      shopName: 'Ashta Hardware & Sanitation Mart',
      rating: 4.4,
      address: { street: 'Main Market, Near Town Square', area: 'Ashta', city: 'Ashta, Sehore', state: 'Madhya Pradesh' },
      location: { coordinates: [76.7222, 23.0195] }
    }
  },
  {
    _id: 'sehore-item-paint',
    id: 'sehore-item-paint',
    name: 'Apex Exterior Emulsion 4L',
    brand: 'Asian Paints',
    category: 'Hardware & Tools',
    description: 'Weatherproof high durability exterior emulsion wall paint.',
    price: 980,
    mrp: 1150,
    unit: 'can',
    quantityInStock: 14,
    lowStockThreshold: 4,
    isAvailable: true,
    stockStatus: 'in_stock',
    images: ['https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=500&q=80'],
    tags: ['paint', 'emulsion', 'ashta'],
    shopId: {
      _id: 'sehore-demo-002',
      id: 'sehore-demo-002',
      shopName: 'Ashta Hardware & Sanitation Mart',
      rating: 4.4,
      address: { street: 'Main Market, Near Town Square', area: 'Ashta', city: 'Ashta, Sehore', state: 'Madhya Pradesh' },
      location: { coordinates: [76.7222, 23.0195] }
    }
  },

  // Ashta Electrical & Farm Centre
  {
    _id: 'sehore-item-wire',
    id: 'sehore-item-wire',
    name: 'Copper House Wire 90m',
    brand: 'Polycab',
    category: 'Electrical & Lighting',
    description: 'Flame retardant FR PVC insulated single core copper wire 2.5 sq mm.',
    price: 1840,
    mrp: 2100,
    unit: 'coil',
    quantityInStock: 3,
    lowStockThreshold: 5,
    isAvailable: true,
    stockStatus: 'low_stock',
    images: ['https://images.unsplash.com/photo-1555963966-b7ae5404b6ed?auto=format&fit=crop&w=500&q=80'],
    tags: ['wire', 'polycab', 'electrical', 'ashta', 'sehore'],
    shopId: {
      _id: 'sehore-demo-003',
      id: 'sehore-demo-003',
      shopName: 'Ashta Electrical & Farm Centre',
      rating: 4.3,
      address: { street: 'Krishi Mandi Road, Ashta', area: 'Ashta', city: 'Ashta, Sehore', state: 'Madhya Pradesh' },
      location: { coordinates: [76.715, 23.018] }
    }
  },
  {
    _id: 'sehore-item-bulb',
    id: 'sehore-item-bulb',
    name: '9W LED Bulb (Cool Day White)',
    brand: 'Syska',
    category: 'Electrical & Lighting',
    description: 'Energy saving B22 base LED bulb with surge protection.',
    price: 110,
    mrp: 140,
    unit: 'piece',
    quantityInStock: 30,
    lowStockThreshold: 8,
    isAvailable: true,
    stockStatus: 'in_stock',
    images: ['https://images.unsplash.com/photo-1550985543-f47f38aeee65?auto=format&fit=crop&w=500&q=80'],
    tags: ['bulb', 'led', 'lighting', 'ashta'],
    shopId: {
      _id: 'sehore-demo-003',
      id: 'sehore-demo-003',
      shopName: 'Ashta Electrical & Farm Centre',
      rating: 4.3,
      address: { street: 'Krishi Mandi Road, Ashta', area: 'Ashta', city: 'Ashta, Sehore', state: 'Madhya Pradesh' },
      location: { coordinates: [76.715, 23.018] }
    }
  },
  {
    _id: 'sehore-item-pump',
    id: 'sehore-item-pump',
    name: '1 HP Mono Block Water Pump',
    brand: 'CRI',
    category: 'Electrical & Lighting',
    description: 'High suction agricultural and domestic self priming centrifugal water pump.',
    price: 4850,
    mrp: 5600,
    unit: 'unit',
    quantityInStock: 2,
    lowStockThreshold: 3,
    isAvailable: true,
    stockStatus: 'low_stock',
    images: ['https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=500&q=80'],
    tags: ['pump', 'motor', 'farm', 'ashta'],
    shopId: {
      _id: 'sehore-demo-003',
      id: 'sehore-demo-003',
      shopName: 'Ashta Electrical & Farm Centre',
      rating: 4.3,
      address: { street: 'Krishi Mandi Road, Ashta', area: 'Ashta', city: 'Ashta, Sehore', state: 'Madhya Pradesh' },
      location: { coordinates: [76.715, 23.018] }
    }
  },

  // Ashta Civil Medical Store
  {
    _id: 'sehore-item-paracetamol',
    id: 'sehore-item-paracetamol',
    name: 'Paracetamol 500mg Tablets',
    brand: 'Calpol',
    category: 'Medicines & Wellness',
    description: 'Fever and general pain relief tablets (strip of 15).',
    price: 28,
    mrp: 32,
    unit: 'strip',
    quantityInStock: 30,
    lowStockThreshold: 8,
    isAvailable: true,
    stockStatus: 'in_stock',
    images: ['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=500&q=80'],
    tags: ['medicine', 'paracetamol', 'fever', 'ashta', 'sehore'],
    shopId: {
      _id: 'sehore-demo-004',
      id: 'sehore-demo-004',
      shopName: 'Ashta Civil Medical Store',
      rating: 4.8,
      address: { street: 'SH-70, Opposite Civil Hospital Ashta', area: 'Ashta', city: 'Ashta, Sehore', state: 'Madhya Pradesh' },
      location: { coordinates: [76.7245, 23.0227] }
    }
  },
  {
    _id: 'sehore-item-ors',
    id: 'sehore-item-ors',
    name: 'ORS Lemon Hydration Sachets (Pack of 5)',
    brand: 'Electral',
    category: 'Medicines & Wellness',
    description: 'WHO recommended formula oral rehydration salts for instant recovery.',
    price: 22,
    mrp: 25,
    unit: 'box',
    quantityInStock: 4,
    lowStockThreshold: 6,
    isAvailable: true,
    stockStatus: 'low_stock',
    images: ['https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=500&q=80'],
    tags: ['ors', 'electral', 'hydration', 'ashta'],
    shopId: {
      _id: 'sehore-demo-004',
      id: 'sehore-demo-004',
      shopName: 'Ashta Civil Medical Store',
      rating: 4.8,
      address: { street: 'SH-70, Opposite Civil Hospital Ashta', area: 'Ashta', city: 'Ashta, Sehore', state: 'Madhya Pradesh' },
      location: { coordinates: [76.7245, 23.0227] }
    }
  },
  {
    _id: 'sehore-item-thermometer',
    id: 'sehore-item-thermometer',
    name: 'Digital Clinical Thermometer',
    brand: 'Dr Morepen',
    category: 'Medicines & Wellness',
    description: 'Fast reading digital thermometer with fever alarm and memory.',
    price: 175,
    mrp: 220,
    unit: 'piece',
    quantityInStock: 12,
    lowStockThreshold: 4,
    isAvailable: true,
    stockStatus: 'in_stock',
    images: ['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=500&q=80'],
    tags: ['thermometer', 'medical', 'ashta'],
    shopId: {
      _id: 'sehore-demo-004',
      id: 'sehore-demo-004',
      shopName: 'Ashta Civil Medical Store',
      rating: 4.8,
      address: { street: 'SH-70, Opposite Civil Hospital Ashta', area: 'Ashta', city: 'Ashta, Sehore', state: 'Madhya Pradesh' },
      location: { coordinates: [76.7245, 23.0227] }
    }
  },
  {
    _id: 'sehore-item-bpmonitor',
    id: 'sehore-item-bpmonitor',
    name: 'Digital BP Monitor (Upper Arm)',
    brand: 'Omron',
    category: 'Medicines & Wellness',
    description: 'Fully automatic blood pressure monitor with Intellisense technology.',
    price: 2150,
    mrp: 2600,
    unit: 'unit',
    quantityInStock: 5,
    lowStockThreshold: 2,
    isAvailable: true,
    stockStatus: 'in_stock',
    images: ['https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=500&q=80'],
    tags: ['bp monitor', 'omron', 'health', 'ashta'],
    shopId: {
      _id: 'sehore-demo-004',
      id: 'sehore-demo-004',
      shopName: 'Ashta Civil Medical Store',
      rating: 4.8,
      address: { street: 'SH-70, Opposite Civil Hospital Ashta', area: 'Ashta', city: 'Ashta, Sehore', state: 'Madhya Pradesh' },
      location: { coordinates: [76.7245, 23.0227] }
    }
  },

  // Bairagarh Electronics & Mobile Hub (Bhopal)
  {
    _id: 'sehore-item-earphones',
    id: 'sehore-item-earphones',
    name: 'Wired Earphones with Mic',
    brand: 'boAt',
    category: 'Electronics & Mobiles',
    description: 'BassHeads high definition audio with in-line microphone and 3.5mm jack.',
    price: 399,
    mrp: 599,
    unit: 'piece',
    quantityInStock: 35,
    lowStockThreshold: 8,
    isAvailable: true,
    stockStatus: 'in_stock',
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=500&q=80'],
    tags: ['earphones', 'boat', 'electronics', 'bairagarh', 'bhopal'],
    shopId: {
      _id: 'sehore-demo-005',
      id: 'sehore-demo-005',
      shopName: 'Bairagarh Electronics & Mobile Hub',
      rating: 4.5,
      address: { street: 'Bairagarh Main Road, Near Bus Stop', area: 'Bairagarh', city: 'Bhopal', state: 'Madhya Pradesh' },
      location: { coordinates: [77.3366, 23.2745] }
    }
  },
  {
    _id: 'sehore-item-charger',
    id: 'sehore-item-charger',
    name: '65W Type-C Fast Charger',
    brand: 'Xiaomi',
    category: 'Electronics & Mobiles',
    description: 'GaN technology ultra-fast wall charger compatible with phones and laptops.',
    price: 799,
    mrp: 999,
    unit: 'piece',
    quantityInStock: 18,
    lowStockThreshold: 5,
    isAvailable: true,
    stockStatus: 'in_stock',
    images: ['https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=500&q=80'],
    tags: ['charger', 'type c', 'fast charging', 'bairagarh', 'bhopal'],
    shopId: {
      _id: 'sehore-demo-005',
      id: 'sehore-demo-005',
      shopName: 'Bairagarh Electronics & Mobile Hub',
      rating: 4.5,
      address: { street: 'Bairagarh Main Road, Near Bus Stop', area: 'Bairagarh', city: 'Bhopal', state: 'Madhya Pradesh' },
      location: { coordinates: [77.3366, 23.2745] }
    }
  },
  {
    _id: 'sehore-item-powerbank',
    id: 'sehore-item-powerbank',
    name: '20000mAh Power Bank',
    brand: 'Redmi',
    category: 'Electronics & Mobiles',
    description: 'Dual output high capacity lithium polymer power bank with 18W fast charging.',
    price: 1499,
    mrp: 1899,
    unit: 'piece',
    quantityInStock: 6,
    lowStockThreshold: 4,
    isAvailable: true,
    stockStatus: 'low_stock',
    images: ['https://images.unsplash.com/photo-1609592426806-a070e176b6d2?auto=format&fit=crop&w=500&q=80'],
    tags: ['powerbank', 'redmi', 'battery', 'bairagarh'],
    shopId: {
      _id: 'sehore-demo-005',
      id: 'sehore-demo-005',
      shopName: 'Bairagarh Electronics & Mobile Hub',
      rating: 4.5,
      address: { street: 'Bairagarh Main Road, Near Bus Stop', area: 'Bairagarh', city: 'Bhopal', state: 'Madhya Pradesh' },
      location: { coordinates: [77.3366, 23.2745] }
    }
  },
  {
    _id: 'sehore-item-ledtv',
    id: 'sehore-item-ledtv',
    name: '32 inch HD Ready Smart TV',
    brand: 'Mi',
    category: 'Electronics & Mobiles',
    description: 'Smart Android LED TV with Dolby Audio, PatchWall and vivid display.',
    price: 12490,
    mrp: 14990,
    unit: 'unit',
    quantityInStock: 3,
    lowStockThreshold: 2,
    isAvailable: true,
    stockStatus: 'low_stock',
    images: ['https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=500&q=80'],
    tags: ['tv', 'smart tv', 'mi', 'bairagarh', 'bhopal'],
    shopId: {
      _id: 'sehore-demo-005',
      id: 'sehore-demo-005',
      shopName: 'Bairagarh Electronics & Mobile Hub',
      rating: 4.5,
      address: { street: 'Bairagarh Main Road, Near Bus Stop', area: 'Bairagarh', city: 'Bhopal', state: 'Madhya Pradesh' },
      location: { coordinates: [77.3366, 23.2745] }
    }
  },

  // New Market Books & Stationery Corner (Bhopal)
  {
    _id: 'sehore-item-notebook',
    id: 'sehore-item-notebook',
    name: 'A4 Long Notebook 200 Pages',
    brand: 'Classmate',
    category: 'Stationery & Office',
    description: 'High brightness ozone treated paper notebook for college and school.',
    price: 95,
    mrp: 120,
    unit: 'book',
    quantityInStock: 48,
    lowStockThreshold: 10,
    isAvailable: true,
    stockStatus: 'in_stock',
    images: ['https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=500&q=80'],
    tags: ['notebook', 'classmate', 'stationery', 'new market', 'bhopal'],
    shopId: {
      _id: 'sehore-demo-006',
      id: 'sehore-demo-006',
      shopName: 'New Market Books & Stationery Corner',
      rating: 4.7,
      address: { street: 'New Market, TT Nagar', area: 'New Market', city: 'Bhopal', state: 'Madhya Pradesh' },
      location: { coordinates: [77.4003, 23.2352] }
    }
  },
  {
    _id: 'sehore-item-paper',
    id: 'sehore-item-paper',
    name: 'A4 Copier Paper Ream 500 Sheets',
    brand: 'BILT',
    category: 'Stationery & Office',
    description: '75 GSM high-opacity multifunction copier paper for printing.',
    price: 265,
    mrp: 310,
    unit: 'ream',
    quantityInStock: 3,
    lowStockThreshold: 5,
    isAvailable: true,
    stockStatus: 'low_stock',
    images: ['https://images.unsplash.com/photo-1586075010923-2dd4570fb338?auto=format&fit=crop&w=500&q=80'],
    tags: ['paper', 'copier', 'office', 'new market'],
    shopId: {
      _id: 'sehore-demo-006',
      id: 'sehore-demo-006',
      shopName: 'New Market Books & Stationery Corner',
      rating: 4.7,
      address: { street: 'New Market, TT Nagar', area: 'New Market', city: 'Bhopal', state: 'Madhya Pradesh' },
      location: { coordinates: [77.4003, 23.2352] }
    }
  },
  {
    _id: 'sehore-item-geometry',
    id: 'sehore-item-geometry',
    name: 'Geometry & Instrument Box',
    brand: 'Camlin',
    category: 'Stationery & Office',
    description: 'Self-centering compass, divider, set squares, protector and scale in sturdy tin case.',
    price: 180,
    mrp: 220,
    unit: 'box',
    quantityInStock: 15,
    lowStockThreshold: 4,
    isAvailable: true,
    stockStatus: 'in_stock',
    images: ['https://images.unsplash.com/photo-1456735190827-d1262f71b8a3?auto=format&fit=crop&w=500&q=80'],
    tags: ['geometry', 'camlin', 'instruments', 'new market'],
    shopId: {
      _id: 'sehore-demo-006',
      id: 'sehore-demo-006',
      shopName: 'New Market Books & Stationery Corner',
      rating: 4.7,
      address: { street: 'New Market, TT Nagar', area: 'New Market', city: 'Bhopal', state: 'Madhya Pradesh' },
      location: { coordinates: [77.4003, 23.2352] }
    }
  },
  {
    _id: 'sehore-item-detergent',
    id: 'sehore-item-detergent',
    name: 'Easy Wash Detergent 1kg',
    brand: 'Surf Excel',
    category: 'Groceries & Daily Essentials',
    description: 'Tough stain removal powder with soothing fragrance.',
    price: 120,
    mrp: 145,
    unit: 'pack',
    quantityInStock: 26,
    lowStockThreshold: 5,
    isAvailable: true,
    stockStatus: 'in_stock',
    images: ['https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=500&q=80'],
    tags: ['detergent', 'surf excel', 'groceries', 'kothri'],
    shopId: {
      _id: 'sehore-demo-001',
      id: 'sehore-demo-001',
      shopName: 'Kothri Kalan Kirana & General Store',
      rating: 4.6,
      address: { street: 'Main Village Road, Kothri Kalan', area: 'Kothri Kalan', city: 'Kothri Kalan, Sehore', state: 'Madhya Pradesh' },
      location: { coordinates: [76.8298, 23.074] }
    }
  },
  {
    _id: 'sehore-item-biscuit',
    id: 'sehore-item-biscuit',
    name: 'Family Pack Biscuits 800g',
    brand: 'Parle',
    category: 'Groceries & Daily Essentials',
    description: 'Crisp and wholesome glucose energy biscuits.',
    price: 35,
    mrp: 40,
    unit: 'pack',
    quantityInStock: 90,
    lowStockThreshold: 15,
    isAvailable: true,
    stockStatus: 'in_stock',
    images: ['https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=500&q=80'],
    tags: ['biscuit', 'parle', 'snacks', 'kothri'],
    shopId: {
      _id: 'sehore-demo-001',
      id: 'sehore-demo-001',
      shopName: 'Kothri Kalan Kirana & General Store',
      rating: 4.6,
      address: { street: 'Main Village Road, Kothri Kalan', area: 'Kothri Kalan', city: 'Kothri Kalan, Sehore', state: 'Madhya Pradesh' },
      location: { coordinates: [76.8298, 23.074] }
    }
  },
  {
    _id: 'sehore-item-hammer',
    id: 'sehore-item-hammer',
    name: 'Steel Claw Hammer 800g',
    brand: 'Taparia',
    category: 'Hardware & Tools',
    description: 'Forged carbon steel claw hammer with shock absorbing grip.',
    price: 340,
    mrp: 395,
    unit: 'piece',
    quantityInStock: 18,
    lowStockThreshold: 4,
    isAvailable: true,
    stockStatus: 'in_stock',
    images: ['https://images.unsplash.com/photo-1586864387967-d02ef85d93e8?auto=format&fit=crop&w=500&q=80'],
    tags: ['hammer', 'taparia', 'tools', 'ashta'],
    shopId: {
      _id: 'sehore-demo-002',
      id: 'sehore-demo-002',
      shopName: 'Ashta Hardware & Sanitation Mart',
      rating: 4.4,
      address: { street: 'Main Market, Near Town Square', area: 'Ashta', city: 'Ashta, Sehore', state: 'Madhya Pradesh' },
      location: { coordinates: [76.7222, 23.0195] }
    }
  },
  {
    _id: 'sehore-item-screws',
    id: 'sehore-item-screws',
    name: 'MS Screws Assorted Pack 100pcs',
    brand: 'Hettich',
    category: 'Hardware & Tools',
    description: 'Corrosion resistant zinc plated wood and wall screws.',
    price: 160,
    mrp: 190,
    unit: 'box',
    quantityInStock: 3,
    lowStockThreshold: 5,
    isAvailable: true,
    stockStatus: 'low_stock',
    images: ['https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?auto=format&fit=crop&w=500&q=80'],
    tags: ['screws', 'hettich', 'fasteners', 'ashta'],
    shopId: {
      _id: 'sehore-demo-002',
      id: 'sehore-demo-002',
      shopName: 'Ashta Hardware & Sanitation Mart',
      rating: 4.4,
      address: { street: 'Main Market, Near Town Square', area: 'Ashta', city: 'Ashta, Sehore', state: 'Madhya Pradesh' },
      location: { coordinates: [76.7222, 23.0195] }
    }
  },
  {
    _id: 'sehore-item-tap',
    id: 'sehore-item-tap',
    name: 'Long Body Brass Tap 15mm',
    brand: 'Cera',
    category: 'Plumbing & Sanitary',
    description: 'Heavy brass body bib tap with aerator and mirror chrome finish.',
    price: 420,
    mrp: 495,
    unit: 'piece',
    quantityInStock: 12,
    lowStockThreshold: 4,
    isAvailable: true,
    stockStatus: 'in_stock',
    images: ['https://images.unsplash.com/photo-1585771724684-38269d6639fd?auto=format&fit=crop&w=500&q=80'],
    tags: ['tap', 'cera', 'plumbing', 'ashta'],
    shopId: {
      _id: 'sehore-demo-002',
      id: 'sehore-demo-002',
      shopName: 'Ashta Hardware & Sanitation Mart',
      rating: 4.4,
      address: { street: 'Main Market, Near Town Square', area: 'Ashta', city: 'Ashta, Sehore', state: 'Madhya Pradesh' },
      location: { coordinates: [76.7222, 23.0195] }
    }
  },
  {
    _id: 'sehore-item-switch',
    id: 'sehore-item-switch',
    name: 'Modular Switch 6A (Pack of 10)',
    brand: 'Anchor',
    category: 'Electrical & Lighting',
    description: 'Spark-shield modular switches with smooth silver contacts.',
    price: 450,
    mrp: 520,
    unit: 'pack',
    quantityInStock: 26,
    lowStockThreshold: 5,
    isAvailable: true,
    stockStatus: 'in_stock',
    images: ['https://images.unsplash.com/photo-1555963966-b7ae5404b6ed?auto=format&fit=crop&w=500&q=80'],
    tags: ['switch', 'anchor', 'electrical', 'ashta'],
    shopId: {
      _id: 'sehore-demo-003',
      id: 'sehore-demo-003',
      shopName: 'Ashta Electrical & Farm Centre',
      rating: 4.3,
      address: { street: 'Krishi Mandi Road, Ashta', area: 'Ashta', city: 'Ashta, Sehore', state: 'Madhya Pradesh' },
      location: { coordinates: [76.715, 23.018] }
    }
  },
  {
    _id: 'sehore-item-board',
    id: 'sehore-item-board',
    name: '4-Socket Extension Board with Fuse',
    brand: 'GM',
    category: 'Electrical & Lighting',
    description: 'Spike guard with master switch, safety shutter and 2m cable.',
    price: 320,
    mrp: 380,
    unit: 'piece',
    quantityInStock: 12,
    lowStockThreshold: 4,
    isAvailable: true,
    stockStatus: 'in_stock',
    images: ['https://images.unsplash.com/photo-1555963966-b7ae5404b6ed?auto=format&fit=crop&w=500&q=80'],
    tags: ['extension', 'board', 'gm', 'ashta'],
    shopId: {
      _id: 'sehore-demo-003',
      id: 'sehore-demo-003',
      shopName: 'Ashta Electrical & Farm Centre',
      rating: 4.3,
      address: { street: 'Krishi Mandi Road, Ashta', area: 'Ashta', city: 'Ashta, Sehore', state: 'Madhya Pradesh' },
      location: { coordinates: [76.715, 23.018] }
    }
  },
  {
    _id: 'sehore-item-torch',
    id: 'sehore-item-torch',
    name: 'Rechargeable LED Torch 3W',
    brand: 'Philips',
    category: 'Electrical & Lighting',
    description: 'High beam long-range rechargeable flashlight for farms and homes.',
    price: 285,
    mrp: 340,
    unit: 'piece',
    quantityInStock: 0,
    lowStockThreshold: 4,
    isAvailable: false,
    stockStatus: 'out_of_stock',
    images: ['https://images.unsplash.com/photo-1550985543-f47f38aeee65?auto=format&fit=crop&w=500&q=80'],
    tags: ['torch', 'philips', 'light', 'ashta'],
    shopId: {
      _id: 'sehore-demo-003',
      id: 'sehore-demo-003',
      shopName: 'Ashta Electrical & Farm Centre',
      rating: 4.3,
      address: { street: 'Krishi Mandi Road, Ashta', area: 'Ashta', city: 'Ashta, Sehore', state: 'Madhya Pradesh' },
      location: { coordinates: [76.715, 23.018] }
    }
  },
  {
    _id: 'sehore-item-cetirizine',
    id: 'sehore-item-cetirizine',
    name: 'Cetirizine 10mg Tablets',
    brand: 'Cetcip',
    category: 'Medicines & Wellness',
    description: 'Non-drowsy anti-allergic relief tablets (strip of 10).',
    price: 19,
    mrp: 24,
    unit: 'strip',
    quantityInStock: 20,
    lowStockThreshold: 5,
    isAvailable: true,
    stockStatus: 'in_stock',
    images: ['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=500&q=80'],
    tags: ['allergy', 'cetirizine', 'medicine', 'ashta'],
    shopId: {
      _id: 'sehore-demo-004',
      id: 'sehore-demo-004',
      shopName: 'Ashta Civil Medical Store',
      rating: 4.8,
      address: { street: 'SH-70, Opposite Civil Hospital Ashta', area: 'Ashta', city: 'Ashta, Sehore', state: 'Madhya Pradesh' },
      location: { coordinates: [76.7245, 23.0227] }
    }
  },
  {
    _id: 'sehore-item-bandage',
    id: 'sehore-item-bandage',
    name: 'Elastic Crepe Bandage 10cm',
    brand: 'Vissco',
    category: 'Medicines & Wellness',
    description: 'Cotton crepe bandage for muscle strain and joint support.',
    price: 145,
    mrp: 175,
    unit: 'piece',
    quantityInStock: 6,
    lowStockThreshold: 5,
    isAvailable: true,
    stockStatus: 'low_stock',
    images: ['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=500&q=80'],
    tags: ['bandage', 'crepe', 'first aid', 'ashta'],
    shopId: {
      _id: 'sehore-demo-004',
      id: 'sehore-demo-004',
      shopName: 'Ashta Civil Medical Store',
      rating: 4.8,
      address: { street: 'SH-70, Opposite Civil Hospital Ashta', area: 'Ashta', city: 'Ashta, Sehore', state: 'Madhya Pradesh' },
      location: { coordinates: [76.7245, 23.0227] }
    }
  },
  {
    _id: 'sehore-item-antacid',
    id: 'sehore-item-antacid',
    name: 'Antacid Gel 200ml',
    brand: 'Digene',
    category: 'Medicines & Wellness',
    description: 'Quick heartburn and acidity relief mint flavored oral gel.',
    price: 135,
    mrp: 150,
    unit: 'bottle',
    quantityInStock: 15,
    lowStockThreshold: 4,
    isAvailable: true,
    stockStatus: 'in_stock',
    images: ['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=500&q=80'],
    tags: ['digene', 'antacid', 'stomach', 'ashta'],
    shopId: {
      _id: 'sehore-demo-004',
      id: 'sehore-demo-004',
      shopName: 'Ashta Civil Medical Store',
      rating: 4.8,
      address: { street: 'SH-70, Opposite Civil Hospital Ashta', area: 'Ashta', city: 'Ashta, Sehore', state: 'Madhya Pradesh' },
      location: { coordinates: [76.7245, 23.0227] }
    }
  },
  {
    _id: 'sehore-item-sanitizer',
    id: 'sehore-item-sanitizer',
    name: 'Hand Sanitizer 500ml',
    brand: 'Dettol',
    category: 'Medicines & Wellness',
    description: 'Alcohol-based germ kill instant hand sanitizer with pump.',
    price: 190,
    mrp: 225,
    unit: 'bottle',
    quantityInStock: 8,
    lowStockThreshold: 5,
    isAvailable: true,
    stockStatus: 'low_stock',
    images: ['https://images.unsplash.com/photo-1584483766114-2cea6facdf57?auto=format&fit=crop&w=500&q=80'],
    tags: ['sanitizer', 'dettol', 'hygiene', 'ashta'],
    shopId: {
      _id: 'sehore-demo-004',
      id: 'sehore-demo-004',
      shopName: 'Ashta Civil Medical Store',
      rating: 4.8,
      address: { street: 'SH-70, Opposite Civil Hospital Ashta', area: 'Ashta', city: 'Ashta, Sehore', state: 'Madhya Pradesh' },
      location: { coordinates: [76.7245, 23.0227] }
    }
  },
  {
    _id: 'sehore-item-mouse',
    id: 'sehore-item-mouse',
    name: 'Wireless Mouse 2.4GHz',
    brand: 'Logitech',
    category: 'Electronics & Mobiles',
    description: 'Ergonomic optical wireless mouse with nano USB receiver.',
    price: 795,
    mrp: 995,
    unit: 'piece',
    quantityInStock: 22,
    lowStockThreshold: 5,
    isAvailable: true,
    stockStatus: 'in_stock',
    images: ['https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=500&q=80'],
    tags: ['mouse', 'logitech', 'electronics', 'bairagarh'],
    shopId: {
      _id: 'sehore-demo-005',
      id: 'sehore-demo-005',
      shopName: 'Bairagarh Electronics & Mobile Hub',
      rating: 4.5,
      address: { street: 'Bairagarh Main Road, Near Bus Stop', area: 'Bairagarh', city: 'Bhopal', state: 'Madhya Pradesh' },
      location: { coordinates: [77.3366, 23.2745] }
    }
  },
  {
    _id: 'sehore-item-cable',
    id: 'sehore-item-cable',
    name: 'Braided USB-C Cable 1m',
    brand: 'boAt',
    category: 'Electronics & Mobiles',
    description: 'Heavy duty tangle-free nylon braided fast charge data cable.',
    price: 199,
    mrp: 299,
    unit: 'piece',
    quantityInStock: 50,
    lowStockThreshold: 10,
    isAvailable: true,
    stockStatus: 'in_stock',
    images: ['https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=500&q=80'],
    tags: ['cable', 'type c', 'boat', 'bairagarh'],
    shopId: {
      _id: 'sehore-demo-005',
      id: 'sehore-demo-005',
      shopName: 'Bairagarh Electronics & Mobile Hub',
      rating: 4.5,
      address: { street: 'Bairagarh Main Road, Near Bus Stop', area: 'Bairagarh', city: 'Bhopal', state: 'Madhya Pradesh' },
      location: { coordinates: [77.3366, 23.2745] }
    }
  },
  {
    _id: 'sehore-item-pens',
    id: 'sehore-item-pens',
    name: 'Blue Ball Pens Pack of 10',
    brand: 'Cello',
    category: 'Stationery & Office',
    description: 'Smooth flow ballpoint pens with fine tip for effortless writing.',
    price: 75,
    mrp: 90,
    unit: 'pack',
    quantityInStock: 0,
    lowStockThreshold: 5,
    isAvailable: false,
    stockStatus: 'out_of_stock',
    images: ['https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=500&q=80'],
    tags: ['pens', 'cello', 'stationery', 'new market'],
    shopId: {
      _id: 'sehore-demo-006',
      id: 'sehore-demo-006',
      shopName: 'New Market Books & Stationery Corner',
      rating: 4.7,
      address: { street: 'New Market, TT Nagar', area: 'New Market', city: 'Bhopal', state: 'Madhya Pradesh' },
      location: { coordinates: [77.4003, 23.2352] }
    }
  },
  {
    _id: 'sehore-item-sticky',
    id: 'sehore-item-sticky',
    name: 'Sticky Notes Cube 3x3',
    brand: '3M Post-it',
    category: 'Stationery & Office',
    description: 'Self adhesive pastel notes pad for reminders and quick memos.',
    price: 95,
    mrp: 120,
    unit: 'pack',
    quantityInStock: 20,
    lowStockThreshold: 4,
    isAvailable: true,
    stockStatus: 'in_stock',
    images: ['https://images.unsplash.com/photo-1586075010923-2dd4570fb338?auto=format&fit=crop&w=500&q=80'],
    tags: ['sticky notes', 'post-it', 'office', 'new market'],
    shopId: {
      _id: 'sehore-demo-006',
      id: 'sehore-demo-006',
      shopName: 'New Market Books & Stationery Corner',
      rating: 4.7,
      address: { street: 'New Market, TT Nagar', area: 'New Market', city: 'Bhopal', state: 'Madhya Pradesh' },
      location: { coordinates: [77.4003, 23.2352] }
    }
  },
  {
    _id: 'sehore-item-marker',
    id: 'sehore-item-marker',
    name: 'Permanent Markers Pack of 4',
    brand: 'Faber-Castell',
    category: 'Stationery & Office',
    description: 'Waterproof bullet tip permanent marker pens in 4 colors.',
    price: 130,
    mrp: 160,
    unit: 'pack',
    quantityInStock: 25,
    lowStockThreshold: 5,
    isAvailable: true,
    stockStatus: 'in_stock',
    images: ['https://images.unsplash.com/photo-1456735190827-d1262f71b8a3?auto=format&fit=crop&w=500&q=80'],
    tags: ['marker', 'faber castell', 'stationery', 'new market'],
    shopId: {
      _id: 'sehore-demo-006',
      id: 'sehore-demo-006',
      shopName: 'New Market Books & Stationery Corner',
      rating: 4.7,
      address: { street: 'New Market, TT Nagar', area: 'New Market', city: 'Bhopal', state: 'Madhya Pradesh' },
      location: { coordinates: [77.4003, 23.2352] }
    }
  },
];

// Helper to generate dates relative to current time
const daysAgo = (days, hours = 0) => new Date(Date.now() - (days * 24 * 60 * 60 * 1000) - (hours * 60 * 60 * 1000)).toISOString();

// Realistic historical reservations/orders across Delhi NCR stores
export let FALLBACK_RESERVATIONS = [
  // TODAY'S ORDERS
  {
    _id: 'res_today_01',
    id: 'res_today_01',
    reservationCode: 'QK-7412',
    customer_id: 'a0000000-0000-0000-0000-000000000001',
    shop_id: 'b0000000-0000-0000-0000-000000000001', // Sharma (Karol Bagh)
    product_name: 'Amul Taaza Milk 1L',
    quantity: 4,
    unit: 'pouch',
    agreed_price: 65,
    total_amount: 260,
    status: 'COMPLETED',
    customer: { name: 'Pooja Verma', phone: '+91 9811002233' },
    created_at: daysAgo(0, 2),
  },
  {
    _id: 'res_today_02',
    id: 'res_today_02',
    reservationCode: 'QK-9831',
    customer_id: 'a0000000-0000-0000-0000-000000000001',
    shop_id: 'b0000000-0000-0000-0000-000000000001', // Sharma
    product_name: 'Finolex 1-inch Heavy Duty PVC Pipe (10ft)',
    quantity: 3,
    unit: 'piece',
    agreed_price: 290,
    total_amount: 870,
    status: 'READY',
    customer: { name: 'Vikas Malhotra', phone: '+91 9877112233' },
    created_at: daysAgo(0, 4),
  },
  {
    _id: 'res_today_03',
    id: 'res_today_03',
    reservationCode: 'QK-5521',
    customer_id: 'a0000000-0000-0000-0000-000000000001',
    shop_id: 'b0000000-0000-0000-0000-000000000001', // Sharma
    product_name: 'Aashirvaad Shudh Chakki Atta (5kg)',
    quantity: 2,
    unit: 'bag',
    agreed_price: 245,
    total_amount: 490,
    status: 'CONFIRMED',
    customer: { name: 'Anita Saxena', phone: '+91 9899334455' },
    created_at: daysAgo(0, 5),
  },
  {
    _id: 'res_today_04',
    id: 'res_today_04',
    reservationCode: 'QK-3190',
    customer_id: 'a0000000-0000-0000-0000-000000000001',
    shop_id: 'b0000000-0000-0000-0000-000000000002', // Gupta (Connaught Place ~2.3km)
    product_name: 'Amul Taaza Milk 1L',
    quantity: 12,
    unit: 'pouch',
    agreed_price: 65,
    total_amount: 780,
    status: 'COMPLETED',
    created_at: daysAgo(0, 3),
  },
  {
    _id: 'res_today_05',
    id: 'res_today_05',
    reservationCode: 'QK-6612',
    customer_id: 'a0000000-0000-0000-0000-000000000001',
    shop_id: 'b0000000-0000-0000-0000-000000000002', // Gupta
    product_name: 'Finolex 1-inch Heavy Duty PVC Pipe (10ft)',
    quantity: 8,
    unit: 'piece',
    agreed_price: 295,
    total_amount: 2360,
    status: 'COMPLETED',
    created_at: daysAgo(0, 6),
  },

  // LAST 7 DAYS
  {
    _id: 'res_7d_01',
    id: 'res_7d_01',
    reservationCode: 'QK-8821',
    shop_id: 'b0000000-0000-0000-0000-000000000001', // Sharma
    product_name: 'Amul Taaza Milk 1L',
    quantity: 48,
    unit: 'pouch',
    agreed_price: 65,
    total_amount: 3120,
    status: 'COMPLETED',
    created_at: daysAgo(2),
  },
  {
    _id: 'res_7d_02',
    id: 'res_7d_02',
    reservationCode: 'QK-1198',
    shop_id: 'b0000000-0000-0000-0000-000000000001', // Sharma
    product_name: 'Aashirvaad Shudh Chakki Atta (5kg)',
    quantity: 35,
    unit: 'bag',
    agreed_price: 245,
    total_amount: 8575,
    status: 'COMPLETED',
    created_at: daysAgo(3),
  },
  {
    _id: 'res_7d_03',
    id: 'res_7d_03',
    reservationCode: 'QK-4402',
    shop_id: 'b0000000-0000-0000-0000-000000000001', // Sharma
    product_name: 'Tata Salt Vacuum Evaporated (1kg)',
    quantity: 28,
    unit: 'packet',
    agreed_price: 28,
    total_amount: 784,
    status: 'COMPLETED',
    created_at: daysAgo(4),
  },
  {
    _id: 'res_7d_04',
    id: 'res_7d_04',
    reservationCode: 'QK-3319',
    shop_id: 'b0000000-0000-0000-0000-000000000001', // Sharma
    product_name: 'Finolex 1-inch Heavy Duty PVC Pipe (10ft)',
    quantity: 32,
    unit: 'piece',
    agreed_price: 290,
    total_amount: 9280,
    status: 'COMPLETED',
    created_at: daysAgo(5),
  },
  {
    _id: 'res_7d_05',
    id: 'res_7d_05',
    reservationCode: 'QK-2984',
    shop_id: 'b0000000-0000-0000-0000-000000000002', // Gupta (~2.3km)
    product_name: 'Amul Taaza Milk 1L',
    quantity: 94,
    unit: 'pouch',
    agreed_price: 65,
    total_amount: 6110,
    status: 'COMPLETED',
    created_at: daysAgo(4),
  },
  {
    _id: 'res_7d_06',
    id: 'res_7d_06',
    reservationCode: 'QK-7744',
    shop_id: 'b0000000-0000-0000-0000-000000000002', // Gupta
    product_name: 'Aashirvaad Shudh Chakki Atta (5kg)',
    quantity: 76,
    unit: 'bag',
    agreed_price: 245,
    total_amount: 18620,
    status: 'COMPLETED',
    created_at: daysAgo(5),
  },
  {
    _id: 'res_7d_07',
    id: 'res_7d_07',
    reservationCode: 'QK-5591',
    shop_id: 'b0000000-0000-0000-0000-000000000002', // Gupta
    product_name: 'Parle-G Gold Biscuits (1kg)',
    quantity: 65,
    unit: 'pack',
    agreed_price: 130,
    total_amount: 8450,
    status: 'COMPLETED',
    created_at: daysAgo(6),
  },
  {
    _id: 'res_7d_08',
    id: 'res_7d_08',
    reservationCode: 'QK-9201',
    shop_id: 'b0000000-0000-0000-0000-000000000003', // City Plumbing (Lajpat Nagar ~9.8km)
    product_name: 'Astral CPVC Pro Pipe 1 inch (3 Meter)',
    quantity: 42,
    unit: 'piece',
    agreed_price: 390,
    total_amount: 16380,
    status: 'COMPLETED',
    created_at: daysAgo(3),
  },
  {
    _id: 'res_7d_09',
    id: 'res_7d_09',
    reservationCode: 'QK-6623',
    shop_id: 'b0000000-0000-0000-0000-000000000003', // City Plumbing
    product_name: 'Tata Salt Vacuum Evaporated (1kg)',
    quantity: 85,
    unit: 'packet',
    agreed_price: 28,
    total_amount: 2380,
    status: 'COMPLETED',
    created_at: daysAgo(4),
  },

  // LAST 30 DAYS
  {
    _id: 'res_30d_01',
    id: 'res_30d_01',
    reservationCode: 'QK-1021',
    shop_id: 'b0000000-0000-0000-0000-000000000001', // Sharma
    product_name: 'Amul Taaza Milk 1L',
    quantity: 380,
    unit: 'pouch',
    agreed_price: 65,
    total_amount: 24700,
    status: 'COMPLETED',
    created_at: daysAgo(15),
  },
  {
    _id: 'res_30d_02',
    id: 'res_30d_02',
    reservationCode: 'QK-1022',
    shop_id: 'b0000000-0000-0000-0000-000000000001', // Sharma
    product_name: 'Aashirvaad Shudh Chakki Atta (5kg)',
    quantity: 240,
    unit: 'bag',
    agreed_price: 245,
    total_amount: 58800,
    status: 'COMPLETED',
    created_at: daysAgo(18),
  },
  {
    _id: 'res_30d_03',
    id: 'res_30d_03',
    reservationCode: 'QK-1023',
    shop_id: 'b0000000-0000-0000-0000-000000000001', // Sharma
    product_name: 'Tata Salt Vacuum Evaporated (1kg)',
    quantity: 190,
    unit: 'packet',
    agreed_price: 28,
    total_amount: 5320,
    status: 'COMPLETED',
    created_at: daysAgo(22),
  },
  {
    _id: 'res_30d_04',
    id: 'res_30d_04',
    reservationCode: 'QK-1024',
    shop_id: 'b0000000-0000-0000-0000-000000000001', // Sharma
    product_name: 'Finolex 1-inch Heavy Duty PVC Pipe (10ft)',
    quantity: 180,
    unit: 'piece',
    agreed_price: 290,
    total_amount: 52200,
    status: 'COMPLETED',
    created_at: daysAgo(24),
  },
  {
    _id: 'res_30d_05',
    id: 'res_30d_05',
    reservationCode: 'QK-2025',
    shop_id: 'b0000000-0000-0000-0000-000000000002', // Gupta (Connaught Place ~2.3km)
    product_name: 'Amul Taaza Milk 1L',
    quantity: 462,
    unit: 'pouch',
    agreed_price: 65,
    total_amount: 30030,
    status: 'COMPLETED',
    created_at: daysAgo(12),
  },
  {
    _id: 'res_30d_06',
    id: 'res_30d_06',
    reservationCode: 'QK-2026',
    shop_id: 'b0000000-0000-0000-0000-000000000002', // Gupta
    product_name: 'Aashirvaad Shudh Chakki Atta (5kg)',
    quantity: 473,
    unit: 'bag',
    agreed_price: 245,
    total_amount: 115885,
    status: 'COMPLETED',
    created_at: daysAgo(20),
  },
  {
    _id: 'res_30d_07',
    id: 'res_30d_07',
    reservationCode: 'QK-2027',
    shop_id: 'b0000000-0000-0000-0000-000000000002', // Gupta
    product_name: 'Tata Salt Vacuum Evaporated (1kg)',
    quantity: 438,
    unit: 'packet',
    agreed_price: 28,
    total_amount: 12264,
    status: 'COMPLETED',
    created_at: daysAgo(25),
  },
  {
    _id: 'res_30d_08',
    id: 'res_30d_08',
    reservationCode: 'QK-2028',
    shop_id: 'b0000000-0000-0000-0000-000000000002', // Gupta
    product_name: 'Parle-G Gold Biscuits (1kg)',
    quantity: 521,
    unit: 'pack',
    agreed_price: 130,
    total_amount: 67730,
    status: 'COMPLETED',
    created_at: daysAgo(21),
  },
  {
    _id: 'res_30d_09',
    id: 'res_30d_09',
    reservationCode: 'QK-3029',
    shop_id: 'b0000000-0000-0000-0000-000000000003', // City Plumbing (~9.8km)
    product_name: 'Astral CPVC Pro Pipe 1 inch (3 Meter)',
    quantity: 290,
    unit: 'piece',
    agreed_price: 390,
    total_amount: 113100,
    status: 'COMPLETED',
    created_at: daysAgo(16),
  },
  {
    _id: 'res_30d_10',
    id: 'res_30d_10',
    reservationCode: 'QK-3030',
    shop_id: 'b0000000-0000-0000-0000-000000000003', // City Plumbing
    product_name: 'Bosch Professional 500W Impact Drill Kit',
    quantity: 34,
    unit: 'kit',
    agreed_price: 2850,
    total_amount: 96900,
    status: 'COMPLETED',
    created_at: daysAgo(27),
  },

  // LAST 90 DAYS (Noida & NCR)
  {
    _id: 'res_90d_01',
    id: 'res_90d_01',
    reservationCode: 'QK-4001',
    shop_id: 'b0000000-0000-0000-0000-000000000004', // Noida (~18.5km)
    product_name: 'Amul Taaza Milk 1L',
    quantity: 1250,
    unit: 'pouch',
    agreed_price: 65,
    total_amount: 81250,
    status: 'COMPLETED',
    created_at: daysAgo(55),
  },
  {
    _id: 'res_90d_02',
    id: 'res_90d_02',
    reservationCode: 'QK-4002',
    shop_id: 'b0000000-0000-0000-0000-000000000004', // Noida
    product_name: 'Aashirvaad Shudh Chakki Atta (5kg)',
    quantity: 890,
    unit: 'bag',
    agreed_price: 245,
    total_amount: 218050,
    status: 'COMPLETED',
    created_at: daysAgo(65),
  },
  {
    _id: 'res_90d_03',
    id: 'res_90d_03',
    reservationCode: 'QK-4003',
    shop_id: 'b0000000-0000-0000-0000-000000000004', // Noida
    product_name: 'Finolex 1-inch Heavy Duty PVC Pipe (10ft)',
    quantity: 610,
    unit: 'piece',
    agreed_price: 290,
    total_amount: 176900,
    status: 'COMPLETED',
    created_at: daysAgo(75),
  },

  // MADHYA PRADESH COMPLETED ORDERS (Sehore, Ashta, Kothri Kalan / VIT Bhopal, Bhopal)
  {
    _id: 'res_mp_01',
    id: 'res_mp_01',
    reservationCode: 'QK-MP101',
    shop_id: 'sehore-demo-001',
    product_name: 'Shudh Chakki Atta 5kg',
    quantity: 35,
    unit: 'bag',
    agreed_price: 245,
    total_amount: 8575,
    status: 'COMPLETED',
    created_at: daysAgo(2),
  },
  {
    _id: 'res_mp_02',
    id: 'res_mp_02',
    reservationCode: 'QK-MP102',
    shop_id: 'sehore-demo-001',
    product_name: 'Everyday Basmati Rice 5kg',
    quantity: 20,
    unit: 'bag',
    agreed_price: 365,
    total_amount: 7300,
    status: 'COMPLETED',
    created_at: daysAgo(5),
  },
  {
    _id: 'res_mp_03',
    id: 'res_mp_03',
    reservationCode: 'QK-MP201',
    shop_id: 'sehore-demo-002',
    product_name: '500W Impact Drill Kit',
    quantity: 12,
    unit: 'kit',
    agreed_price: 2850,
    total_amount: 34200,
    status: 'COMPLETED',
    created_at: daysAgo(3),
  },
  {
    _id: 'res_mp_04',
    id: 'res_mp_04',
    reservationCode: 'QK-MP202',
    shop_id: 'sehore-demo-002',
    product_name: 'PVC Pipe 1 inch (10ft)',
    quantity: 50,
    unit: 'piece',
    agreed_price: 290,
    total_amount: 14500,
    status: 'COMPLETED',
    created_at: daysAgo(8),
  },
  {
    _id: 'res_mp_05',
    id: 'res_mp_05',
    reservationCode: 'QK-MP301',
    shop_id: 'sehore-demo-003',
    product_name: 'Copper House Wire 90m',
    quantity: 15,
    unit: 'coil',
    agreed_price: 1840,
    total_amount: 27600,
    status: 'COMPLETED',
    created_at: daysAgo(4),
  },
  {
    _id: 'res_mp_06',
    id: 'res_mp_06',
    reservationCode: 'QK-MP302',
    shop_id: 'sehore-demo-003',
    product_name: '1 HP Mono Block Water Pump',
    quantity: 4,
    unit: 'unit',
    agreed_price: 4850,
    total_amount: 19400,
    status: 'COMPLETED',
    created_at: daysAgo(12),
  },
  {
    _id: 'res_mp_07',
    id: 'res_mp_07',
    reservationCode: 'QK-MP401',
    shop_id: 'sehore-demo-004',
    product_name: 'Digital BP Monitor (Upper Arm)',
    quantity: 8,
    unit: 'unit',
    agreed_price: 2150,
    total_amount: 17200,
    status: 'COMPLETED',
    created_at: daysAgo(1),
  },
  {
    _id: 'res_mp_08',
    id: 'res_mp_08',
    reservationCode: 'QK-MP402',
    shop_id: 'sehore-demo-004',
    product_name: 'Digital Clinical Thermometer',
    quantity: 25,
    unit: 'piece',
    agreed_price: 175,
    total_amount: 4375,
    status: 'COMPLETED',
    created_at: daysAgo(6),
  },
  {
    _id: 'res_mp_09',
    id: 'res_mp_09',
    reservationCode: 'QK-MP501',
    shop_id: 'sehore-demo-005',
    product_name: '32 inch HD Ready Smart TV',
    quantity: 5,
    unit: 'unit',
    agreed_price: 12490,
    total_amount: 62450,
    status: 'COMPLETED',
    created_at: daysAgo(7),
  },
  {
    _id: 'res_mp_10',
    id: 'res_mp_10',
    reservationCode: 'QK-MP502',
    shop_id: 'sehore-demo-005',
    product_name: '20000mAh Power Bank',
    quantity: 18,
    unit: 'piece',
    agreed_price: 1499,
    total_amount: 26982,
    status: 'COMPLETED',
    created_at: daysAgo(14),
  },
  {
    _id: 'res_mp_11',
    id: 'res_mp_11',
    reservationCode: 'QK-MP601',
    shop_id: 'sehore-demo-006',
    product_name: 'A4 Copier Paper Ream 500 Sheets',
    quantity: 40,
    unit: 'ream',
    agreed_price: 265,
    total_amount: 10600,
    status: 'COMPLETED',
    created_at: daysAgo(10),
  },
  {
    _id: 'res_mp_12',
    id: 'res_mp_12',
    reservationCode: 'QK-MP602',
    shop_id: 'sehore-demo-006',
    product_name: 'A4 Long Notebook 200 Pages',
    quantity: 80,
    unit: 'book',
    agreed_price: 95,
    total_amount: 7600,
    status: 'COMPLETED',
    created_at: daysAgo(18),
  },
];

// Rich Customer Product Requests with Bargain / Taraju state machine
export let FALLBACK_CUSTOMER_REQUESTS = [
  {
    _id: 'req_cust_001',
    id: 'req_cust_001',
    productName: 'Amul Taaza Milk 1L',
    productImage: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=600&q=80',
    category: 'Groceries & Daily Essentials',
    quantity: 2,
    unit: 'pouch',
    shopStock: 8,
    customerOffer: 58,
    currentPrice: 65,
    status: 'PENDING', // PENDING | BARGAINING | ACCEPTED | REJECTED | CONFIRMED
    urgency: 'immediate',
    customerName: 'Aman Deep Singh',
    customerPhone: '+91 9811884422',
    notes: 'Need 2 packets urgently for evening tea and kids.',
    createdAt: daysAgo(0, 1),
    negotiationHistory: [
      {
        sender: 'customer',
        senderName: 'Aman Deep Singh',
        offer: 58,
        message: 'Can you give ₹58? Taking 2 packets.',
        time: daysAgo(0, 1),
      }
    ],
  },
  {
    _id: 'req_cust_002',
    id: 'req_cust_002',
    productName: 'Finolex 1-inch Heavy Duty PVC Pipe (10ft)',
    productImage: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?auto=format&fit=crop&w=600&q=80',
    category: 'Plumbing & Sanitary',
    quantity: 10,
    unit: 'piece',
    shopStock: 45,
    customerOffer: 270,
    currentPrice: 290,
    status: 'BARGAINING',
    urgency: 'today',
    customerName: 'Rajesh Plumbers',
    customerPhone: '+91 9877443311',
    notes: 'Urgent plumbing repair job at Karol Bagh building.',
    createdAt: daysAgo(0, 2),
    negotiationHistory: [
      {
        sender: 'customer',
        senderName: 'Rajesh Plumbers',
        offer: 260,
        message: 'Can you give ₹260 for bulk 10 pieces?',
        time: daysAgo(0, 2),
      },
      {
        sender: 'shopkeeper',
        senderName: 'Sharma Hardware',
        offer: 275,
        message: 'I can offer ₹275 with priority counter dispatch.',
        time: daysAgo(0, 1),
      },
      {
        sender: 'customer',
        senderName: 'Rajesh Plumbers',
        offer: 270,
        message: '₹270 final? Coming in 15 mins.',
        time: daysAgo(0, 0),
      }
    ],
  },
  {
    _id: 'req_cust_003',
    id: 'req_cust_003',
    productName: 'Bosch Professional 500W Impact Drill Kit',
    productImage: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=600&q=80',
    category: 'Hardware & Tools',
    quantity: 1,
    unit: 'kit',
    shopStock: 8,
    customerOffer: 2650,
    currentPrice: 2850,
    status: 'PENDING',
    urgency: 'today',
    customerName: 'Sanjay Kumar',
    customerPhone: '+91 9911223388',
    notes: 'Contractor on site, need genuine Bosch with warranty card.',
    createdAt: daysAgo(0, 3),
    negotiationHistory: [
      {
        sender: 'customer',
        senderName: 'Sanjay Kumar',
        offer: 2650,
        message: 'Can you match ₹2650? Paying cash at pickup.',
        time: daysAgo(0, 3),
      }
    ],
  },
  {
    _id: 'req_cust_004',
    id: 'req_cust_004',
    productName: 'Astral CPVC Pro Pipe 1 inch (3 Meter)',
    productImage: 'https://images.unsplash.com/photo-1542013936693-884638332954?auto=format&fit=crop&w=600&q=80',
    category: 'Plumbing & Sanitary',
    quantity: 2,
    unit: 'piece',
    shopStock: 3, // Low stock warning in shop!
    customerOffer: 360,
    currentPrice: 390,
    status: 'BARGAINING',
    urgency: 'immediate',
    customerName: 'Rohit Sharma',
    customerPhone: '+91 9811556677',
    notes: 'Burst hot water line repair.',
    createdAt: daysAgo(0, 4),
    negotiationHistory: [
      {
        sender: 'customer',
        senderName: 'Rohit Sharma',
        offer: 350,
        message: 'Can you give ₹350 each?',
        time: daysAgo(0, 4),
      },
      {
        sender: 'shopkeeper',
        senderName: 'Sharma Hardware',
        offer: 375,
        message: 'I only have 3 left, ₹375 is fair.',
        time: daysAgo(0, 3),
      },
      {
        sender: 'customer',
        senderName: 'Rohit Sharma',
        offer: 365,
        message: 'Can you do ₹365? Picking up now.',
        time: daysAgo(0, 2),
      }
    ],
  }
];
